export const cursos = [
    {
      nome: 'ADMINISTRAÇÃO',
      PTG: 3,
      LLE: 1,
      MTM: 3,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 2,
      RDC: 3,
      DSC: 2,
    },
    {
      nome: 'AGRONOMIA',
      PTG: 1,
      LLE: 1,
      MTM: 1.5,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 2,
    },
    {
      nome: 'AGRONOMIA - CURITIBANOS',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'ANIMAÇÃO',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'ANTROPOLOGIA',
      PTG: 1.5,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 2,
    },
    {
      nome: 'ARQUITETURA E URBANISMO',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'ARQUIVOLOGIA',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'ARTES CÊNICAS',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'BIBLIOTECONOMIA',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'CIÊNCIAS DA COMPUTAÇÃO',
      PTG: 1,
      LLE: 1,
      MTM: 3,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 3,
    },
    {
      nome: 'CIÊNCIA DA INFORMAÇÃO',
      PTG: 1,
      LLE: 1,
      MTM: 2,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1,
      DSC: 1,
    },
    {
      nome: 'CIÊNCIA E TECNOLOGIA',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1,
      DSC: 1,
    },
    {
      nome: 'CIÊNCIA E TECNOLOGIA DE ALIMENTOS',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1,
      DSC: 1,
    },
    {
      nome: 'CIÊNCIAS BIOLÓGICAS',
      PTG: 2,
      LLE: 1,
      MTM: 1,
      BLG: 2,
      QMC: 1,
      FSC: 1,
      CHS: 2,
      RDC: 3,
      DSC: 2,
    },
    {
      nome: 'CIÊNCIAS CONTÁBEIS',
      PTG: 2,
      LLE: 1,
      MTM: 2,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'CIÊNCIAS ECONÔMICAS',
      PTG: 2,
      LLE: 1,
      MTM: 2,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 2,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'CIÊNCIAS SOCIAIS',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'CINEMA',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'DESIGN',
      PTG: 2,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 3,
      DSC: 2,
    },
    {
      nome: 'DESIGN DE PRODUTO',
      PTG: 2,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 3,
      DSC: 1,
    },
    {
      nome: 'DIREITO',
      PTG: 2,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 2,
      DSC: 1,
    },
    {
      nome: 'EDUCAÇÃO FÍSICA',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'ENFERMAGEM',
      PTG: 2,
      LLE: 1,
      MTM: 1,
      BLG: 2,
      QMC: 1.5,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'ENGENHARIA AEROESPACIAL',
      PTG: 2,
      LLE: 1,
      MTM: 4,
      BLG: 1,
      QMC: 1,
      FSC: 3,
      CHS: 1,
      RDC: 1.5,
      DSC: 2,
    },
    {
      nome: 'ENGENHARIA AUTOMOTIVA',
      PTG: 2,
      LLE: 1,
      MTM: 4,
      BLG: 1,
      QMC: 1,
      FSC: 3,
      CHS: 1,
      RDC: 2,
      DSC: 1,
    },
    {
      nome: 'ENGENHARIA CIVIL',
      PTG: 2,
      LLE: 1,
      MTM: 4,
      BLG: 1,
      QMC: 1,
      FSC: 3,
      CHS: 1,
      RDC: 1.5,
      DSC: 2,
    },
    {
      nome: 'ENGENHARIA CIVIL DE INFRAESTRUTURA',
      PTG: 2,
      LLE: 1,
      MTM: 2,
      BLG: 1,
      QMC: 1,
      FSC: 2,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'ENGENHARIA DE ALIMENTOS',
      PTG: 2,
      LLE: 1.5,
      MTM: 4,
      BLG: 1,
      QMC: 2,
      FSC: 3,
      CHS: 1,
      RDC: 1.5,
      DSC: 2,
    },
    {
      nome: 'ENGENHARIA DE AQUICULTURA',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'ENGENHARIA DE COMPUTAÇÃO',
      PTG: 2,
      LLE: 1,
      MTM: 4,
      BLG: 1,
      QMC: 1,
      FSC: 3,
      CHS: 1,
      RDC: 1.5,
      DSC: 2,
    },
    {
      nome: 'ENGENHARIA DE CONTROLE E AUTOMAÇÃO',
      PTG: 2,
      LLE: 1,
      MTM: 4,
      BLG: 1,
      QMC: 1,
      FSC: 3,
      CHS: 1,
      RDC: 1.5,
      DSC: 2,
    },
    {
      nome: 'ENGENHARIA DE ENERGIA',
      PTG: 2,
      LLE: 1,
      MTM: 4,
      BLG: 1,
      QMC: 1,
      FSC: 3,
      CHS: 1,
      RDC: 1.5,
      DSC: 2,
    },
    {
      nome: 'ENGENHARIA DE MATERIAIS',
      PTG: 2,
      LLE: 1,
      MTM: 4,
      BLG: 1,
      QMC: 1,
      FSC: 3,
      CHS: 1,
      RDC: 1.5,
      DSC: 2,
    },
    {
      nome: 'ENGENHARIA DE PRODUÇÃO',
      PTG: 2,
      LLE: 1,
      MTM: 4,
      BLG: 1,
      QMC: 1,
      FSC: 3,
      CHS: 1,
      RDC: 1.5,
      DSC: 2,
    },
    {
      nome: 'ENGENHARIA DE TRANSPORTES E LOGÍSTICA',
      PTG: 2,
      LLE: 1,
      MTM: 4,
      BLG: 1,
      QMC: 1,
      FSC: 3,
      CHS: 1,
      RDC: 1.5,
      DSC: 2,
    },
    {
      nome: 'ENGENHARIA ELÉTRICA',
      PTG: 2,
      LLE: 1,
      MTM: 4,
      BLG: 1,
      QMC: 1,
      FSC: 3,
      CHS: 1,
      RDC: 1.5,
      DSC: 2,
    },
    {
      nome: 'ENGENHARIA ELETRÔNICA',
      PTG: 2,
      LLE: 1,
      MTM: 4,
      BLG: 1,
      QMC: 1,
      FSC: 3,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'ENGENHARIA FERROVIÁRIA E METROVIÁRIA',
      PTG: 2,
      LLE: 1,
      MTM: 4,
      BLG: 1,
      QMC: 1,
      FSC: 3,
      CHS: 1,
      RDC: 2,
      DSC: 1,
    },
    {
      nome: 'ENGENHARIA FLORESTAL',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1,
      DSC: 1,
    },
    {
      nome: 'ENGENHARIA MECÂNICA',
      PTG: 2,
      LLE: 1,
      MTM: 4,
      BLG: 1,
      QMC: 1,
      FSC: 3,
      CHS: 1,
      RDC: 2,
      DSC: 2,
    },
    {
      nome: 'ENGENHARIA MECATRÔNICA',
      PTG: 2,
      LLE: 1,
      MTM: 4,
      BLG: 1,
      QMC: 1,
      FSC: 3,
      CHS: 1,
      RDC: 2,
      DSC: 1,
    },
    {
      nome: 'ENGENHARIA NAVAL',
      PTG: 2,
      LLE: 1,
      MTM: 3,
      BLG: 1,
      QMC: 1,
      FSC: 2,
      CHS: 1,
      RDC: 1,
      DSC: 1,
    },
    {
      nome: 'ENGENHARIA QUÍMICA',
      PTG: 2,
      LLE: 1,
      MTM: 4,
      BLG: 1,
      QMC: 1,
      FSC: 3,
      CHS: 1,
      RDC: 1.5,
      DSC: 2,
    },
    {
      nome: 'ENGENHARIA SANITÁRIA E AMBIENTAL',
      PTG: 2,
      LLE: 1,
      MTM: 4,
      BLG: 1,
      QMC: 1,
      FSC: 3,
      CHS: 1,
      RDC: 1.5,
      DSC: 2,
    },
    {
      nome: 'ENGENHARIA TÊXTIL',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 2,
      DSC: 1,
    },
    {
      nome: 'FARMÁCIA',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1.5,
      QMC: 1.5,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'FILOSOFIA',
      PTG: 1.5,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1.5,
      RDC: 1.5,
      DSC: 1.5,
    },
    {
      nome: 'FÍSICA',
      PTG: 2,
      LLE: 1,
      MTM: 2,
      BLG: 1,
      QMC: 1,
      FSC: 2,
      CHS: 1,
      RDC: 1,
      DSC: 1,
    },
    {
      nome: 'FISIOTERAPIA',
      PTG: 2,
      LLE: 1,
      MTM: 1,
      BLG: 2,
      QMC: 1.5,
      FSC: 1.5,
      CHS: 1,
      RDC: 3,
      DSC: 2.5,
    },
    {
      nome: 'FONOAUDIOLOGIA',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'GEOGRAFIA',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'GEOLOGIA',
      PTG: 1,
      LLE: 1,
      MTM: 2,
      BLG: 1,
      QMC: 2,
      FSC: 2,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'HISTÓRIA',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'JORNALISMO',
      PTG: 3,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 2,
      RDC: 3,
      DSC: 1,
    },
    {
      nome: 'LETRAS - ALEMÃO',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'LETRAS - ESPANHOL',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'LETRAS - FRANCÊS',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'LETRAS - INGLÊS',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'LETRAS - ITALIANO',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'LETRAS - PORTUGUÊS',
      PTG: 4,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 2,
      RDC: 4,
      DSC: 1,
    },
    {
      nome: 'MATEMÁTICA',
      PTG: 2,
      LLE: 1,
      MTM: 2,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'MATEMÁTICA - BLUMENAU',
      PTG: 1,
      LLE: 1,
      MTM: 2,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1,
      DSC: 1,
    },
    {
      nome: 'MEDICINA',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'MEDICINA VETERINÁRIA',
      PTG: 1,
      LLE: 1,
      MTM: 1.5,
      BLG: 1.5,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 2,
    },
    {
      nome: 'METEOROLOGIA',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 2,
      DSC: 1,
    },
    {
      nome: 'MUSEOLOGIA',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'NUTRIÇÃO',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 2,
      DSC: 1,
    },
    {
      nome: 'OCEANOGRAFIA',
      PTG: 3,
      LLE: 1,
      MTM: 3,
      BLG: 1,
      QMC: 2,
      FSC: 2,
      CHS: 1,
      RDC: 3,
      DSC: 1,
    },
    {
      nome: 'ODONTOLOGIA',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'PEDAGOGIA',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'PSICOLOGIA',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'QUÍMICA',
      PTG: 2,
      LLE: 1,
      MTM: 2,
      BLG: 1,
      QMC: 2,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'QUÍMICA - BLUMENAU',
      PTG: 1,
      LLE: 1,
      MTM: 2,
      BLG: 1,
      QMC: 2,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'QUÍMICA INDUSTRIAL',
      PTG: 1,
      LLE: 1,
      MTM: 2,
      BLG: 1,
      QMC: 2,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'RELAÇÕES INTERNACIONAIS',
      PTG: 2,
      LLE: 1,
      MTM: 2,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1.5,
      RDC: 2,
      DSC: 1,
    },
    {
      nome: 'SERVIÇO SOCIAL',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1.5,
      RDC: 1,
      DSC: 1,
    },
    {
      nome: 'SISTEMAS DE INFORMAÇÃO',
      PTG: 1,
      LLE: 1,
      MTM: 3,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1,
      DSC: 3,
    },
    {
      nome: 'TECNOLOGIAS DA INFORMAÇÃO E COMUNICAÇÃO',
      PTG: 1,
      LLE: 1,
      MTM: 1.5,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    {
      nome: 'ZOOTECNIA',
      PTG: 1,
      LLE: 1,
      MTM: 1,
      BLG: 1,
      QMC: 1,
      FSC: 1,
      CHS: 1,
      RDC: 1.5,
      DSC: 1,
    },
    
  ];
  